FROM golang:1.21.6-alpine3.18 AS build

RUN adduser --disabled-password --home /app -u 10001 app

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY *.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/docker-app

FROM scratch
COPY --from=build /app/docker-app /app/docker-app

COPY --from=build /etc/passwd /etc/passwd
USER app

EXPOSE 8080

# Run
CMD ["/app/docker-app"]